travis:
  secure:
    BINSTAR_TOKEN: L6VemcWB6ZU2QjtZc6mfsIlnsRuDy86KliQAUwkKaXL80nijECCtaBwdBhqa9TKE1e3J8Uet8Dc6V17Z9kCyvXkaH/mXPQCVdJfuBeZFm6/1zdMC7ZNQQtQo14YiEEqE2peKWjZT88OQ4WtJiz7QL/kFL7d5higsHFYrkwtdUKHmUi9peYxuajFxAtUBJRKF2Hox64Ye/0NLWMT1BtyriR1D7veds8oPFczJhj6qgOSL22QWhcBi18LOOZq4urzke8SzTCWErl1yjuEobNJo59rKaF6novVEY73PNMmtq/4w1Ynq5nT4SS0d/2e2VSFzs7RwbTsyZ5As0Ft86cDLQA3BbT+M7iinq/SyZ2PB468lBzovyJk+/HPt2wK8d3+rk8LORaNxvZNNi3ug905Fh4f2qzlcC9cP3VI/+VVRCEU/50tFFooZJMYmAliHKGA+eAmcLrRKVFPZNXNt+1BbWZVTDic62ZhR6ejVIpr2pAPziKUQm6O+GApKZvbcuJLb5yIwMZPOlM08yDQAos+6PUOGU0nbw88I70+glPds3OXhhHdY6TDkt33QxpSzGur8lKgPmnRmpp6xg+v6Nj7iTv5+V7oqJ/wTOtEK8w112lOWygpYr9eqLrluDf3tl+kvRzApxa+fn/cOvxpTrHQShzMD6mM+6Hj4fxSfG477pE0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
